**Theory Questions**

 Q1.Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?
 A-Purpose of NumPy: NumPy (Numerical Python) is a fundamental library in Python used for scientific computing and data analysis. Its primary purpose is to provide support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays. It enhances Python’s capabilities in numerical computation and serves as a foundation for other data science libraries like Pandas, SciPy, and scikit-learn.

Advantages of NumPy:

Efficient Data Structures:

NumPy arrays (ndarrays) are more efficient than Python lists for storing and processing large amounts of data. The arrays use contiguous memory locations, enabling faster access and modification compared to traditional lists.
Vectorized Operations:

NumPy allows for vectorized operations, which eliminate the need for explicit loops. This means operations like addition, multiplication, and other element-wise calculations can be done directly on the entire array, leading to concise and readable code.
Performance Optimization:

NumPy is implemented in C, which makes it significantly faster for numerical computations compared to regular Python code. It provides optimized routines for numerical operations, reducing execution time for large-scale computations.
Broad Functionality:

NumPy offers a wide range of functions, including statistical, linear algebra, and random number generation capabilities. This makes it versatile for various scientific applications.
Memory Efficiency:

NumPy arrays are stored more compactly in memory, which is crucial when dealing with large datasets. This is because they require less overhead than Python lists and use fixed data types.
Broadcasting and Vectorization:

NumPy supports broadcasting, which allows you to perform arithmetic operations on arrays of different shapes without creating unnecessary copies of data. This makes array operations more intuitive and efficient.
Integration with Other Libraries:

NumPy integrates seamlessly with other data science libraries, such as Pandas for data manipulation, Matplotlib for data visualization, and SciPy for scientific computations. This interoperability makes it a central component of the Python scientific ecosystem.
Overall, NumPy enhances Python's capabilities by offering a high-performance, easy-to-use framework for numerical and data-intensive computations.

 Q2.Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?
 A-Both np.mean() and np.average() are used to calculate the central tendency of data in NumPy, but they have some key differences in their functionality and usage.

1. np.mean() Function:
Purpose: Computes the arithmetic mean (average) along the specified axis.
Syntax: np.mean(array, axis=None, dtype=None, out=None, keepdims=False)
Parameters:
array: Input array for which the mean needs to be computed.
axis: Axis or axes along which the means are computed. Default is None, meaning it computes the mean of all elements.
dtype: Data type of the output array. By default, it is the same as the input array’s dtype.
out: Optional output array to store the result.
keepdims: If set to True, the reduced axes are left in the result as dimensions with size one.
2. np.average() Function:
Purpose: Computes the weighted average of the input array elements. If no weights are provided, it behaves the same as np.mean().
Syntax: np.average(array, axis=None, weights=None, returned=False)
Parameters:
array: Input array for which the average needs to be computed.
axis: Axis or axes along which to compute the average. Default is None, meaning it computes the average of all elements.
weights: An array of weights associated with the values in array. Must be the same shape as array. If None, all elements are assumed to have equal weight.
returned: If set to True, returns a tuple (average, sum_of_weights) instead of just the average.
3. Key Differences:
Weighted Average vs. Simple Average:

np.mean() always calculates a simple mean, giving equal weight to all elements.
np.average() can compute a weighted mean if weights are provided. Without weights, it defaults to calculating a simple mean like np.mean().
Additional Output:

np.average() has an additional returned parameter that, when set to True, returns the sum of weights along with the average. This feature is not available in np.mean().
Efficiency:

For a basic average calculation, np.mean() is slightly more efficient since it doesn’t involve the overhead of handling weights.
4. When to Use Each Function:
Use np.mean() for standard average calculations when there is no need to assign different weights to the elements.
Use np.average() when dealing with weighted data or if you need to calculate the sum of weights along with the average.
Understanding when to use np.mean() versus np.average() can be crucial depending on the context of the data analysis, such as calculating a weighted grade or computing a simple mean of numerical data.



Q3.Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.
A-NumPy provides several methods to reverse arrays along different axes depending on the shape and dimensionality of the array. Below, we'll cover a few of the common techniques to reverse 1D, 2D, and n-dimensional arrays.

1. Reversing a 1D Array:
To reverse a one-dimensional array, you can use slicing or the np.flip() function.
2. Reversing a 2D Array:
For 2D arrays, you can reverse the elements along different axes (rows or columns) using slicing or np.flip().

Reversing Rows (axis=0): To reverse the rows of a 2D array, you can use slicing or specify axis=0 in np.flip().
3. Reversing n-Dimensional Arrays:
For arrays with more than two dimensions, np.flip() can be applied along a specific axis. Alternatively, you can use slicing with negative step sizes along the desired axis.
4. Specialized Functions for Flipping Arrays:
NumPy also provides specialized functions like np.fliplr() and np.flipud() for 2D arrays.

 Q4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.
 A-Determining the Data Type in a NumPy Array:

In NumPy, the data type of an array's elements can be checked using the dtype attribute.


In [2]:
import numpy as np

arr = np.array([1, 2, 3])
print(arr.dtype)


int64


In [3]:
arr = np.array([1, 2, 3], dtype='float32')
print(arr.dtype)


float32


Importance of Data Types in Memory Management and Performance:

Memory Efficiency:

NumPy arrays are more memory-efficient compared to standard Python lists because they store elements of a single data type, ensuring compact storage.
For example, an int8 array (8-bit integers) uses four times less memory than a float32 array (32-bit floats) for the same number of elements.
Performance Optimization:

The choice of data type directly impacts the performance of numerical operations. Using the smallest possible data type that can hold the data without loss of precision results in faster computations.
For example, operations on an int8 array are faster than on a float64 array because smaller data types require fewer CPU cycles.
Consistency and Data Integrity:

Choosing the appropriate data type helps maintain consistency and avoid unexpected behavior during operations. For example, using float64 instead of int32 for division prevents truncation errors.
NumPy’s support for custom data types (e.g., complex128 for complex numbers) ensures precise representation and manipulation of specialized data.
Broadcasting and Type Conversion:

When performing operations between arrays of different data types, NumPy uses upcasting rules to determine the output type. Understanding and controlling data types helps prevent unnecessary upcasting, which could lead to increased memory usage.
In summary, correctly determining and selecting data types in NumPy arrays is essential for optimizing memory usage, achieving high computational performance, and maintaining numerical accuracy.

Q5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
A-An ndarray (N-dimensional array) is the core data structure provided by NumPy. It is a grid of values, all of the same type, indexed by a tuple of non-negative integers. Unlike Python’s built-in data structures, such as lists, ndarrays are highly optimized for mathematical and numerical operations.
Key Features of ndarrays:
Homogeneous Data Type:

All elements in an ndarray must be of the same data type (e.g., int32, float64, bool), ensuring consistent and predictable behavior during computations.
Multidimensional Support:

An ndarray can have multiple dimensions (1D, 2D, 3D, or higher), making it suitable for complex data structures like matrices, tensors, and multidimensional grids.
The dimensions of the array are defined by its shape, represented as a tuple of integers. For example, a 2D array with shape (3, 4) has 3 rows and 4 columns.
Memory Efficiency:

ndarrays are stored in contiguous blocks of memory, unlike Python lists, which are pointers to individual objects. This compact memory layout improves access times and reduces the memory overhead.
Mathematical Operations:

NumPy supports a wide range of mathematical operations on ndarrays, including element-wise addition, subtraction, multiplication, division, matrix operations, and linear algebra routines.
Operations on ndarrays are vectorized, meaning they are applied simultaneously to all elements, eliminating the need for explicit loops.
Broadcasting:

Broadcasting is a powerful feature that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes without copying data. It automatically adjusts the shapes of arrays so that operations like addition and multiplication can be performed efficiently.
Indexing and Slicing:

NumPy arrays offer advanced indexing and slicing capabilities for selecting and modifying data. You can extract entire sub-arrays or individual elements using simple and complex slicing techniques.
Support for Mathematical Functions:

NumPy provides a rich set of built-in mathematical functions (sin, cos, exp, dot, etc.) optimized for ndarrays. These functions can be applied to entire arrays in one step, making it easy to implement complex algorithms.
Differences Between ndarrays and Python Lists:
Data Type Consistency:

Python Lists: Can contain elements of different data types (e.g., int, float, str in a single list).
NumPy ndarrays: All elements must be of the same data type, making them more predictable and faster for numerical computations.
Memory and Performance:

Python Lists: Each element is an independent Python object, stored as a pointer, which leads to higher memory consumption and slower access times.
NumPy ndarrays: Stored in contiguous blocks of memory, which ensures faster access and efficient memory usage.
Mathematical Operations:

Python Lists: Cannot perform element-wise arithmetic operations directly (e.g., addition or multiplication of lists).
NumPy ndarrays: Support element-wise operations, matrix operations, and broadcasting, enabling complex numerical manipulations.
Multidimensional Support:

Python Lists: Can create nested lists to represent 2D or 3D data, but operations on these nested structures are cumbersome and not optimized.
NumPy ndarrays: Naturally support multidimensional data, with shape and dimensions attributes (shape, ndim) for easy manipulation.
Indexing and Slicing:

Python Lists: Basic indexing and slicing capabilities, but limited when dealing with nested lists.
NumPy ndarrays: Advanced indexing, slicing, and masking functionalities that allow fine-grained control over data selection.
In summary, ndarrays provide a more efficient and versatile data structure for numerical and scientific computing compared to standard Python lists. They are specifically designed to handle large datasets and perform complex mathematical operations, making them the preferred choice for data analysis and scientific applications.

Q6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
A-NumPy arrays (ndarrays) offer significant performance benefits over standard Python lists, especially for large-scale numerical computations. These advantages arise due to factors such as memory efficiency, speed of operation, and support for vectorized operations. Below, we analyze some of the key benefits:

1. Memory Efficiency:
Compact Memory Layout:

NumPy arrays store data in a contiguous block of memory, which leads to efficient memory utilization.
Python lists, on the other hand, store references to objects, causing higher memory overhead.
Homogeneous Data Type:

All elements in a NumPy array share the same data type, making it possible to store them compactly in memory without storing type information for each element.
Python lists can contain mixed data types, resulting in additional memory being used for each element’s type and value.
2. Speed and Computational Efficiency:
Element-wise Operations:

NumPy performs element-wise operations directly at the compiled C level, whereas Python lists require explicit looping, leading to slower execution.
Vectorization:

NumPy’s vectorized operations eliminate the need for explicit Python loops, reducing overhead and speeding up computations.
Broadcasting:

Broadcasting allows NumPy to perform arithmetic operations on arrays of different shapes without additional data duplication or complex logic, leading to efficient execution.
3. Built-in Mathematical Functions:
NumPy provides a rich set of optimized mathematical functions (e.g., sin, cos, exp, sqrt), which are faster and more memory-efficient compared to iterating over elements and applying Python’s math functions.
These operations are implemented in C, making them significantly faster for large datasets.
4. Support for Multidimensional Data:
NumPy arrays natively support multidimensional data structures such as matrices and tensors, allowing complex data manipulation and matrix operations.
Python lists can only represent multidimensional data through nested lists, which are cumbersome to handle and less efficient in terms of both memory and speed.
5. Advanced Indexing and Slicing:
NumPy allows for advanced indexing, slicing, and masking operations, which enable quick extraction and modification of array elements without the need for multiple nested loops.
This results in more concise and optimized code compared to similar operations using nested Python lists.
6. Parallelization and Hardware Optimization:
Many NumPy functions are optimized to take advantage of parallel processing, using libraries like BLAS and LAPACK to execute operations on multiple CPU cores or even GPU, providing additional speedup for large-scale operations.
Python lists do not benefit from such optimizations, making NumPy the preferred choice for computationally intensive tasks.

Q7.Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.
A-Use vstack() when you need to add new rows to an existing array.
Use hstack() when you need to add new columns to an existing array.
The key difference lies in the axis along which the stacking operation is performed: axis 0 for vstack() and axis 1 for hstack().

In [4]:
import numpy as np

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8, 9]])

#Vertical stack
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7],
                 [8]])

# Horizontal stacking
result = np.hstack((arr1, arr2))
print(result)


[[1 2 3 7]
 [4 5 6 8]]


Q8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.
A-1. numpy.fliplr() – Flip Left to Right:
Description: fliplr() flips the elements of a 2D array horizontally (left to right).

Effect: It reverses the order of columns while keeping the rows unchanged.

Applicable Dimensions: The input must be at least a 2D array; using it on a 1D array will result in an error.

Axis of Operation: Operates along axis 1 (the horizontal axis).
2. numpy.flipud() – Flip Up to Down:
Description: flipud() flips the elements of an array vertically (up to down).

Effect: It reverses the order of rows while keeping the columns unchanged.

Applicable Dimensions: It works on arrays of any dimension (1D, 2D, or higher).

Axis of Operation: Operates along axis 0 (the vertical axis).

Q9.Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?
A-numpy.array_split() is a flexible and robust method for splitting arrays, particularly when the splits are uneven.
It ensures that sub-arrays have nearly equal sizes and does not raise an error when the array cannot be evenly divided.
This behavior makes array_split() a preferred choice over split() in scenarios where exact division is not possible.
How array_split() Handles Uneven Splits:
When the number of elements does not divide evenly into the specified number of sections, array_split() distributes the "extra" elements among the first few sub-arrays.

 Q10.Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?
 A-1. Vectorization in NumPy
Definition: Vectorization refers to the process of applying operations to entire arrays (vectors) simultaneously, rather than iterating through individual elements using loops.

Mechanism: In NumPy, operations are performed at a low level using compiled C code. This allows NumPy to take advantage of CPU optimizations and perform operations in parallel, making computations much faster.

Benefits:

Performance: Vectorized operations eliminate the overhead of Python’s for-loops, reducing the number of interpreted operations.
Readability: Vectorized code is more concise and easier to read because it abstracts away the looping logic.
2. Broadcasting in NumPy
Definition: Broadcasting is a mechanism that allows NumPy to perform arithmetic operations on arrays of different shapes and sizes by automatically expanding their dimensions to match each other.

Purpose: It simplifies operations between arrays of different shapes without requiring explicit replication of data. This saves both memory and computational time.

How It Works:

When performing operations between two arrays, NumPy compares their shapes element-wise, starting from the last dimension. Two dimensions are compatible if:
They are equal, or
One of them is 1 (allowing for expansion).
If the shapes are not compatible, broadcasting is not possible, and NumPy raises a ValueError.
How Vectorization and Broadcasting Contribute to Efficient Array Operations
Elimination of Explicit Loops:

Both vectorization and broadcasting eliminate the need for looping through array elements. Looping in Python is slow due to its interpreted nature, whereas vectorized operations in NumPy are executed at a lower level using optimized C code.
Memory Efficiency:

Broadcasting avoids the need to create large temporary arrays by "logically" expanding the smaller array without actually replicating data in memory.
This results in less memory consumption and faster execution times, especially for large datasets.
Parallel Execution:

Many vectorized operations in NumPy are executed in parallel, leveraging CPU optimizations and SIMD (Single Instruction, Multiple Data) instructions, which improve speed and throughput.
Concise and Readable Code:

Vectorized and broadcasted operations are often represented by a single line of code, making it easier to understand and maintain compared to traditional looping constructs.
Numerical Stability:

Using vectorized operations helps prevent errors that can occur in explicit looping, such as incorrect indexing or off-by-one errors.

**PRACTCAL QUESTIONS**

Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.


In [6]:
import numpy as np

# Step 1: Create a 3x3 NumPy array with random integers between 1 and 100
array = np.random.randint(1, 101, size=(3, 3))
print("Original Array:\n", array)

# Step 2: Interchange rows and columns using transpose
transposed_array = array.T
print("\nTransposed Array:\n", transposed_array)


Original Array:
 [[64 79 70]
 [51 84 86]
 [63  5 11]]

Transposed Array:
 [[64 51 63]
 [79 84  5]
 [70 86 11]]


Q2. 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [7]:
import numpy as np

# Step 1: Create a 1D NumPy array with 10 elements (0 to 9)
array_1d = np.arange(10)
print("1D Array:\n", array_1d)

# Step 2: Reshape the 1D array into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)
print("\n2x5 Array:\n", array_2x5)

# Step 3: Reshape the 2x5 array into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)
print("\n5x2 Array:\n", array_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]

2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]

5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


 Q3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [8]:
import numpy as np

# Step 1: Create a 4x4 NumPy array with random float values between 0 and 1
array_4x4 = np.random.rand(4, 4)
print("Original 4x4 Array:\n", array_4x4)

# Step 2: Add a border of zeros around the 4x4 array to make it 6x6
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)
print("\nArray with Zero Border (6x6):\n", array_6x6)


Original 4x4 Array:
 [[0.61452781 0.83410906 0.65177416 0.01013447]
 [0.45829325 0.23538307 0.59715952 0.44455737]
 [0.3655643  0.75707179 0.85318519 0.81987719]
 [0.56446965 0.38590836 0.56850612 0.75897095]]

Array with Zero Border (6x6):
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.61452781 0.83410906 0.65177416 0.01013447 0.        ]
 [0.         0.45829325 0.23538307 0.59715952 0.44455737 0.        ]
 [0.         0.3655643  0.75707179 0.85318519 0.81987719 0.        ]
 [0.         0.56446965 0.38590836 0.56850612 0.75897095 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [9]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
array = np.arange(10, 61, 5)
print("Array of integers from 10 to 60 with a step of 5:\n", array)


Array of integers from 10 to 60 with a step of 5:
 [10 15 20 25 30 35 40 45 50 55 60]


Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [10]:
import numpy as np

# Step 1: Create a NumPy array of strings
array_strings = np.array(['python', 'numpy', 'pandas'])

# Step 2: Apply different case transformations
uppercase_array = np.char.upper(array_strings)  # Convert to uppercase
lowercase_array = np.char.lower(array_strings)  # Convert to lowercase
titlecase_array = np.char.title(array_strings)   # Convert to title case

# Step 3: Print the results
print("Original Array:\n", array_strings)
print("\nUppercase Array:\n", uppercase_array)
print("\nLowercase Array:\n", lowercase_array)
print("\nTitle Case Array:\n", titlecase_array)


Original Array:
 ['python' 'numpy' 'pandas']

Uppercase Array:
 ['PYTHON' 'NUMPY' 'PANDAS']

Lowercase Array:
 ['python' 'numpy' 'pandas']

Title Case Array:
 ['Python' 'Numpy' 'Pandas']


Q6.Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [11]:
import numpy as np

# Step 1: Create a NumPy array of words
array_words = np.array(['python', 'numpy', 'pandas'])

# Step 2: Insert a space between each character of every word
spaced_array = np.char.join(' ', array_words)  # Join with a space

# Step 3: Print the results
print("Original Array:\n", array_words)
print("\nArray with Spaces Between Characters:\n", spaced_array)


Original Array:
 ['python' 'numpy' 'pandas']

Array with Spaces Between Characters:
 ['p y t h o n' 'n u m p y' 'p a n d a s']


Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [12]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8, 9],
                   [10, 11, 12]])

# Step 2: Perform element-wise operations
addition_result = array1 + array2          # Element-wise addition
subtraction_result = array1 - array2       # Element-wise subtraction
multiplication_result = array1 * array2    # Element-wise multiplication
division_result = array1 / array2          # Element-wise division

# Step 3: Print the results
print("Array 1:\n", array1)
print("\nArray 2:\n", array2)
print("\nElement-wise Addition:\n", addition_result)
print("\nElement-wise Subtraction:\n", subtraction_result)
print("\nElement-wise Multiplication:\n", multiplication_result)
print("\nElement-wise Division:\n", division_result)


Array 1:
 [[1 2 3]
 [4 5 6]]

Array 2:
 [[ 7  8  9]
 [10 11 12]]

Element-wise Addition:
 [[ 8 10 12]
 [14 16 18]]

Element-wise Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]

Element-wise Multiplication:
 [[ 7 16 27]
 [40 55 72]]

Element-wise Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [13]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:\n", identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diagonal(identity_matrix)
# Alternatively, you can use:
# diagonal_elements = np.diag(identity_matrix)

print("\nDiagonal Elements:\n", diagonal_elements)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal Elements:
 [1. 1. 1. 1. 1.]


Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array

In [14]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1001, size=100)
print("Random Integers:\n", random_integers)

# Step 2: Define a function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Step 3: Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

# Step 4: Display the prime numbers
print("\nPrime Numbers in the Array:\n", prime_numbers)


Random Integers:
 [285 241 793 820 917 248 467 347 175 243 165 474 272 753 664 710 475 574
 302 237 284 587 776 600 643 724 440 965 714 695  32 792 674 623 790 312
  38 854 457 281 903 672 949 679 473 604  61 345 430 706 571  52  58 457
 470 828 425 569 546 361 598 196  78 466 338 343 832 375 444 196 723 319
 695 348 928 290 118 334 597 488 168 489 258 222 903 580 239 577  14 210
  33 845 438  58 764 357 837 643 399 130]

Prime Numbers in the Array:
 [241, 467, 347, 587, 643, 457, 281, 61, 571, 457, 569, 239, 577, 643]


Q10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [20]:
import numpy as np
np.random.seed(0)
daily_temperatures = np.random.randint(15, 35, size=30)
print("Daily Temperatures for a Month:\n", daily_temperatures)
weekly_temperatures = daily_temperatures.reshape(3, 10)
weekly_averages = np.mean(weekly_temperatures, axis=1)
print("\nWeekly Temperatures:\n", weekly_temperatures)
print("\nWeekly Average Temperatures:\n", weekly_averages)

Daily Temperatures for a Month:
 [27 30 15 18 18 22 24 34 33 19 21 27 16 21 22 29 32 20 28 23 24 34 31 34
 20 30 30 15 33 18]

Weekly Temperatures:
 [[27 30 15 18 18 22 24 34 33 19]
 [21 27 16 21 22 29 32 20 28 23]
 [24 34 31 34 20 30 30 15 33 18]]

Weekly Average Temperatures:
 [24.  23.9 26.9]
